export enum Configuration {
  PORT = 'PORT',
  HOST = 'HOST',
  DB_TYPE = 'DB_TYPE',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_DATABASE = 'DB_DATABASE',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  GQL_PLAYGROUND = 'GQL_PLAYGROUND',
  GQL_FILE_NAME = 'GQL_FILE_NAME',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRE_IN = 'JWT_EXPIRE_IN',
}
